default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5433
  username: postgres
  password: postgres

development:
  <<: *default
  database: drgfia_development
test:
  <<: *default
  database: drgfia_test

production:
  <<: *default
  database: drgfia_production
  port: 5433
  username: drgfia
  password: <%= ENV['DRGFIA_DATABASE_PASSWORD'] %>

